package supermemo;

/**
 * An implementation of a supermemo (or other similar) algorithm, to be used with a set of test
 * data.
 */
public interface SuperMemoAlgorithm {

    /**
     * Set the list of items this algorithm is to be run on.
     *
     * @param items - a List of Items
     */
//  public void setItems(List items);
    /**
     * Return all the items to be tested today.
     *
     * @param day - int starting at day 0
     * @return - a Collection of items to be iteratoed over
     */
//  public Collection getItems(int day);
    /**
     * Processes an item for the day. 5 - perfect response 4 - correct response after a hesitation 3
     * - correct response recalled with serious difficulty 2 - incorrect response; where the correct
     * one seemed easy to recall 1 - incorrect response; the correct one remembered 0 - complete
     * blackout.
     *
     * @param item  - the item from the list
     * @param score - the score generated by the user from 0-5
     */
    public void testItem(Item item, int score);
}
