/*
 * Copyright (C) 2014 Daddy.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301  USA
 */
package hanzihelper;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Daddy
 */
public class ReviewPanel extends javax.swing.JPanel {

    FlashcardDeck flashcards;

    /**
     * Creates new form ReviewPanel
     */
    public ReviewPanel(CharRecord record, ReviewOptions reviewOptions) {
        flashcards = new FlashcardDeck(record, reviewOptions);
        initComponents();
        setQuestionDisplay();
        setCardText();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reviewChar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pinyinLabel = new javax.swing.JLabel();
        chapLabel = new javax.swing.JLabel();
        defLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        countLabel = new javax.swing.JLabel();
        showButton = new javax.swing.JButton();
        wrongButton = new javax.swing.JButton();
        correctButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(400, 360));

        reviewChar.setFont(new java.awt.Font("SimSun", 0, 100)); // NOI18N
        reviewChar.setText("汉");
        reviewChar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        pinyinLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pinyinLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pinyinLabel.setText("pinyin");

        chapLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chapLabel.setText("Book Chapter X");

        defLabel.setFont(new java.awt.Font("Arial Unicode MS", 0, 16)); // NOI18N
        defLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        defLabel.setText("Definition");

        buttonPanel.setBackground(new java.awt.Color(255, 255, 255));

        countLabel.setText("01/100");
        countLabel.setAlignmentX(0.5F);

        showButton.setText("Show");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });

        wrongButton.setText("Wrong");
        wrongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrongButtonActionPerformed(evt);
            }
        });

        correctButton.setText("Correct");
        correctButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(wrongButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correctButton)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(countLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addComponent(countLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showButton)
                    .addComponent(wrongButton)
                    .addComponent(correctButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 58, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(chapLabel)
                            .addComponent(defLabel)
                            .addComponent(pinyinLabel)
                            .addComponent(reviewChar)
                            .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(66, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(reviewChar)
                .addGap(42, 42, 42)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pinyinLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(defLabel)
                .addGap(18, 18, 18)
                .addComponent(chapLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
        setAnswerDisplay();
        flashcards.playSound();
    }//GEN-LAST:event_showButtonActionPerformed

    private void correctButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctButtonActionPerformed
        // TODO add your handling code here:
        flashcards.answerCorrect();
        if (flashcards.hasNext()) {
            setQuestionDisplay();
            setCardText();
        } else { // We're done here
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
            frame.dispose();
        }
    }//GEN-LAST:event_correctButtonActionPerformed

    private void wrongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrongButtonActionPerformed
        flashcards.answerWrong();
        setQuestionDisplay();
        setCardText();
    }//GEN-LAST:event_wrongButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel chapLabel;
    private javax.swing.JButton correctButton;
    private javax.swing.JLabel countLabel;
    private javax.swing.JLabel defLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel pinyinLabel;
    private javax.swing.JLabel reviewChar;
    private javax.swing.JButton showButton;
    private javax.swing.JButton wrongButton;
    // End of variables declaration//GEN-END:variables

    public void setCardText() {
        flashcards.prepareSound();
        reviewChar.setText(flashcards.getChars());
        pinyinLabel.setText(flashcards.getPinyinColorized());
        defLabel.setText(flashcards.getDefinition());
        chapLabel.setText(flashcards.getBookAndChapter());
        countLabel.setText(flashcards.getCardCount());
    }

    public void setQuestionDisplay() {
        pinyinLabel.setVisible(false);
        defLabel.setVisible(false);
        chapLabel.setVisible(false);
        countLabel.setVisible(true);
        showButton.setEnabled(true);
        wrongButton.setEnabled(false);
        correctButton.setEnabled(false);
    }

    public void setAnswerDisplay() {
        pinyinLabel.setVisible(true);
        defLabel.setVisible(true);
        chapLabel.setVisible(true);
        countLabel.setVisible(true);
        showButton.setEnabled(false);
        wrongButton.setEnabled(true);
        correctButton.setEnabled(true);
    }
}
